# Generated by Django 4.2.7 on 2023-11-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.URLField(),
        ),
    ]
